# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170819_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='internal_description',
            field=models.CharField(max_length=20),
        ),
    ]
