# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170819_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='internal_description',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
