# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_other_internal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='internal_description',
            field=models.CharField(max_length=20),
        ),
    ]
