# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170819_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other',
            old_name='price',
            new_name='price_in_cents',
        ),
    ]
