# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Anonymous', max_length=30)),
                ('val1', models.IntegerField(default=0)),
                ('val2', models.IntegerField(default=0)),
                ('val3', models.IntegerField(default=0)),
                ('books', models.IntegerField(default=0)),
                ('class_of', models.CharField(default='N/A', max_length=6)),
            ],
        ),
    ]
