# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_auto_20170819_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('product_ID', models.IntegerField()),
                ('item_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('person', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='OtherOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('product_ID', models.IntegerField()),
                ('item_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('person', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Other')),
            ],
        ),
    ]
